import { NextResponse } from 'next/server';

export async function GET() {
    // Live Data path (generated by python script)
    const fs = require('fs');
    const path = require('path');
    const dataPath = path.join(process.cwd(), 'src/app/api/stats/data.json');

    try {
        if (fs.existsSync(dataPath)) {
            const fileData = fs.readFileSync(dataPath, 'utf8');
            const realStats = JSON.parse(fileData);

            // Return the full data structure including metadata
            if (realStats.leaderboard && Array.isArray(realStats.leaderboard)) {
                return NextResponse.json({
                    generated_at: realStats.generated_at,
                    version: realStats.version,
                    total_tasks: realStats.total_tasks,
                    repositories: realStats.repositories,
                    categories: realStats.categories,
                    leaderboard: realStats.leaderboard
                });
            } else if (Array.isArray(realStats)) {
                // Legacy format - wrap in expected structure
                return NextResponse.json({
                    leaderboard: realStats,
                    total_tasks: 50,
                    repositories: {},
                    categories: {}
                });
            }
        }
    } catch (e) {
        console.error("Error reading live stats:", e);
    }

    // Fallback: REALISTIC SIMULATION with full structure
    const simulatedStats = {
        generated_at: new Date().toISOString(),
        version: "1.0",
        total_tasks: 50,
        repositories: {
            "flask": { language: "python", tasks: 5, full_name: "pallets/flask" },
            "lodash": { language: "javascript", tasks: 4, full_name: "lodash/lodash" },
            "fastapi": { language: "python", tasks: 5, full_name: "tiangolo/fastapi" },
            "ui": { language: "javascript", tasks: 6, full_name: "shadcn-ui/ui" },
            "query": { language: "javascript", tasks: 4, full_name: "TanStack/query" },
            "openai-python": { language: "python", tasks: 4, full_name: "openai/openai-python" },
            "next.js": { language: "javascript", tasks: 6, full_name: "vercel/next.js" },
            "pydantic": { language: "python", tasks: 5, full_name: "pydantic/pydantic" },
            "django": { language: "python", tasks: 6, full_name: "django/django" },
            "react": { language: "javascript", tasks: 5, full_name: "facebook/react" }
        },
        categories: {
            "stale_drift": "Code uses deprecated/legacy patterns",
            "security_drift": "Code introduces security vulnerabilities",
            "architecture_drift": "Code violates architectural boundaries",
            "pattern_drift": "Code deviates from established patterns",
            "logic_drift": "Code has logical inconsistencies"
        },
        leaderboard: [
            {
                model: "anthropic/claude-3.5-sonnet",
                slug: "anthropic_claude-3.5-sonnet",
                display_name: "Claude 3.5 Sonnet",
                provider: "Anthropic",
                pass_rate: 94.2,
                drift_detection_rate: 94.2,
                accuracy: 96.0,
                fpr: 0.1,
                tasks_run: 50,
                status: "Simulated",
                verified_at: "2026-01-28",
                rank: 1,
                breakdown: {
                    by_repo: {
                        "lodash": { passed: 4, failed: 0, total: 4 },
                        "django": { passed: 5, failed: 1, total: 6 },
                        "react": { passed: 5, failed: 0, total: 5 },
                        "fastapi": { passed: 5, failed: 0, total: 5 }
                    },
                    by_language: {
                        "javascript": { passed: 23, failed: 2, total: 25 },
                        "python": { passed: 24, failed: 1, total: 25 }
                    },
                    by_category: {
                        "stale_drift": { passed: 12, failed: 0, total: 12 },
                        "security_drift": { passed: 9, failed: 1, total: 10 },
                        "pattern_drift": { passed: 14, failed: 1, total: 15 }
                    }
                }
            },
            {
                model: "openai/gpt-4o",
                slug: "openai_gpt-4o",
                display_name: "GPT-4o",
                provider: "OpenAI",
                pass_rate: 92.8,
                drift_detection_rate: 92.8,
                accuracy: 94.0,
                fpr: 0.2,
                tasks_run: 50,
                status: "Simulated",
                verified_at: "2026-01-29",
                rank: 2,
                breakdown: {
                    by_repo: {
                        "lodash": { passed: 4, failed: 0, total: 4 },
                        "django": { passed: 4, failed: 2, total: 6 },
                        "react": { passed: 4, failed: 1, total: 5 },
                        "fastapi": { passed: 5, failed: 0, total: 5 }
                    },
                    by_language: {
                        "javascript": { passed: 22, failed: 3, total: 25 },
                        "python": { passed: 24, failed: 1, total: 25 }
                    },
                    by_category: {
                        "stale_drift": { passed: 11, failed: 1, total: 12 },
                        "security_drift": { passed: 8, failed: 2, total: 10 },
                        "pattern_drift": { passed: 13, failed: 2, total: 15 }
                    }
                }
            },
            {
                model: "openai/o1-preview",
                slug: "openai_o1-preview",
                display_name: "o1-preview",
                provider: "OpenAI",
                pass_rate: 91.5,
                drift_detection_rate: 91.5,
                accuracy: 93.0,
                fpr: 0.5,
                tasks_run: 50,
                status: "Simulated",
                verified_at: "2026-01-30",
                rank: 3,
                breakdown: {
                    by_repo: {
                        "lodash": { passed: 3, failed: 1, total: 4 },
                        "django": { passed: 5, failed: 1, total: 6 },
                        "react": { passed: 4, failed: 1, total: 5 }
                    },
                    by_language: {
                        "javascript": { passed: 21, failed: 4, total: 25 },
                        "python": { passed: 24, failed: 1, total: 25 }
                    },
                    by_category: {
                        "stale_drift": { passed: 10, failed: 2, total: 12 },
                        "security_drift": { passed: 9, failed: 1, total: 10 },
                        "pattern_drift": { passed: 12, failed: 3, total: 15 }
                    }
                }
            },
            {
                model: "meta/llama-3.1-405b",
                slug: "meta_llama-3.1-405b",
                display_name: "Llama 3.1 405B",
                provider: "Meta",
                pass_rate: 88.9,
                drift_detection_rate: 88.9,
                accuracy: 90.0,
                fpr: 0.8,
                tasks_run: 50,
                status: "Simulated",
                verified_at: "2026-01-30",
                rank: 4,
                breakdown: {
                    by_repo: {
                        "lodash": { passed: 3, failed: 1, total: 4 },
                        "django": { passed: 4, failed: 2, total: 6 },
                        "react": { passed: 3, failed: 2, total: 5 }
                    },
                    by_language: {
                        "javascript": { passed: 20, failed: 5, total: 25 },
                        "python": { passed: 22, failed: 3, total: 25 }
                    },
                    by_category: {
                        "stale_drift": { passed: 9, failed: 3, total: 12 },
                        "security_drift": { passed: 7, failed: 3, total: 10 },
                        "pattern_drift": { passed: 11, failed: 4, total: 15 }
                    }
                }
            }
        ]
    };

    return NextResponse.json(simulatedStats);
}
